### ISSUE TITLE
[Bug]: "Not enough biome ID's available to add all dimensions."

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [PG85/OpenTerrainGenerator#1009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to create a world I get that error

### Expected Behavior

Being able to create a world completely fine

### Which platforms have you reproduced this issue using?

Forge Single Player

### OTG Version

OTG 1.12.2-v9.5-R2.jar

### Platform Version

1.12.2

### Steps To Reproduce

To reproduce try to create a world

### Log file

[latest.log](https://github.com/user-attachments/files/17282916/latest.log)

### Anything else?

I am using the Biomes Bundle O Plenty mod with this mod and I have the JustEnoughIDs mod installed, I think I saw people saying this was fixed awhile ago but it doesn't seemed fixed.
I am also using default config files.

**Comment by NLBlackEagle** [comment]
This was fixed for 1.16.5 but never for 1.12.2 given how 1.12 works the hard limit of 256 biomes couldn't be increased except through the usage of virtual biomes which shortly explained pose as normal biomes but are internally handled in a way that allows them to be different in terms of terrain and population.

Your best shot is to look at what kind of biome mods you have and remove the ones with a lot of non-virtual biomes. OTG presets mostly all make use of virtual biomes so those don't tend to take up a whole lot of biome slots.

**Comment by MagmaSlime123** [comment]
Install Roughly Enough IDs.

https://www.curseforge.com/minecraft/mc-mods/reid

**Comment by IdkWhatNameThingyToPut** [comment]
> Install Roughly Enough IDs.
> 
> https://www.curseforge.com/minecraft/mc-mods/reid

Just tried it with the Roughly Enough IDs mod and it doesn't work unfortunately. Still getting the "Not enough biome ID's available to add all dimensions." error.

**Comment by IdkWhatNameThingyToPut** [comment]
> This was fixed for 1.16.5 but never for 1.12.2 given how 1.12 works the hard limit of 256 biomes couldn't be increased except through the usage of virtual biomes which shortly explained pose as normal biomes but are internally handled in a way that allows them to be different in terms of terrain and population.
> 
> Your best shot is to look at what kind of biome mods you have and remove the ones with a lot of non-virtual biomes. OTG presets mostly all make use of virtual biomes so those don't tend to take up a whole lot of biome slots.

Ohh ok thanks um so after looking at previous biome id to name dumps with the TellMe mod I can see it's at around 261 biome IDs listed. Could I ask please what biome ID amount would you suggest to be around to get this mod to work?I I know I may need to remove some biomes/clear up some biome IDs as it is to get this mod to work but I'm just curious on what number I should actually be aiming for? Also how many biome IDs etc does the Biome Bundle O Plenty preset take up? And I'm just curious is there a better way to see what mods are taking up all the biome IDs/virtual biome IDs?

**Comment by IdkWhatNameThingyToPut** [comment]
After removing Traverse Reforged (It was already on my modpack and I accidently didn't remove it before testing with this mod and stuff) and with 244 biome IDs listed in a new dump from the TellMe mod everything is working fine now. Anyway Merry Christmas everyone
